### ISSUE TITLE
Community events funding

### ISSUE THREAD

**Issue by manics** [uk-tre/community-management#60]
### Detail

We have some funding available as part of the current grant.

### Actions

- How much is available?
- What is the deadline for spending it?
- Can it be used to pay in advance for events after the deadline?
- [x] Make proposal for both a [working group co-working day](https://hackmd.io/nTAAo7fOT_quE18y0NYjnA) and a [documentation day](https://hackmd.io/ty_bEhtBTrKjmYsJEEP8Qw)
- [x] Get clarity on what is possible to spend it on and by when (payed in March for things in the future)
- [x] Make proposals to the community and get feedback
- [x] Decide by 20th Feb

**Comment by Davsarper** [comment]
- Could potentially use for future event (in person) as long as invoice comes in before end of funding (Balint to check)
- There could be some accesibility or support costs for remote events as well
- Think of an event that does make sense to ahve, for exmaple support creation of Governance (maybe not for CMWG but for necessary support and assistance like proper notetaking, documentaiton, people who ensure the transparency of the process)

**Comment by KirstieJane** [comment]
I think getting the chairs of the working groups together in person would be a great use of the funding.

In the meeting on 6 Feb we discussed the tension between writing the governance for WGs and _then_ inviting WG chairs to an in person collaboration session vs having a session scheduled to bring the WG members / chairs _into_ the writing of the governance documentation.

I feel quite strongly that having the small group write and _then_ bring the WG chairs together misses an opportunity to set culture for people across the community to participate and see themselves as having agency in building the documentation.

The flip side from others in the room was that it may end up being just a small group who do the writing _either way_ so why not focus tightly on getting the first complete draft together and then sharing it with the WG chairs / members. Maybe more pragmatic and maybe what would end up happening anyway!

The other point that I think is important is to actively reach out to people in the community who _could_ chair working groups. (I think of these as proto-working groups) rather than only engaging with people who currently have expressed interest in chairing a working group. The reason for this is that you'll get a very biased group of people who proactively put themselves forward to chair a WG in the absence of any governance and we need the community to have more diverse representation and leadership than that!

My suggestion there was to go back to the breakout room topics that have been popular at community events and reach out to people who have been active in those topics and ask them to be at the event. They don't need to commit to anything but you need their voices in the room 😸 

The

**Comment by Davsarper** [comment]
@harisood and I have brainstormed two possible events that we think would be worth organising, during the next meeting we will decide wheter to move forward with these or propose different activities. 
- Documentation sprints, to collaboratively finalise the first version of our governance documentation (https://hackmd.io/ty_bEhtBTrKjmYsJEEP8Qw)
- Working groups day: to get interested WGs through the set up process and help them success (https://hackmd.io/nTAAo7fOT_quE18y0NYjnA)
We feel that these represent good events for the current stage the community is at - getting all our infrastructure set up properly, and getting some working groups up and running.

**Comment by manics** [comment]
I like the idea of the Working groups setup and prep day. We'd need to make a big push to get people to propose a WG in advance, but I prefer that over an earlier idea of getting the WG chairs together to write a Governance doc.

Having input from the WG chairs on the Governance doc is obviously important, but the WG chairs are just one of the stakeholders who's input is required. It's equally important to have input from the community on how they want official WGs to work, since they're the ones who will be contributing, supporting, and consuming the results.

**Comment by Davsarper** [comment]
We have the capacity to fund this event beyond March by reprofiling grant and increasing DI person time (which we are inveesting in the project) and Turing will later cover the costs for the event

**Comment by Davsarper** [comment]
Community feedback was positive and we will organise these two events in specific issues
