### ISSUE TITLE
Talk at HDR UK Conference

### ISSUE THREAD

**Issue by harisood** [uk-tre/community-management#63]
### Detail

I've been invited to give a 5-10 minute lightning talk at the HDR UK conference on the UK TRE Community.

The ask:
```
I’d really like to let people know about this new community group and how it has rapidly evolved over the past year or so. The key messages are about collaboration across the community really helping TREs to mature and support interoperability and federated projects. Explaining how it evolved from 30 people at the RSE conference in 22 to ~200 this year. Perhaps you could also mention SATRE and the collaboration cafes (or do a double act for that with Chris Cole). We have an action packed agenda and so maybe only 5-10 mins of high level overview (confirming agenda at the moment). Perhaps cover how the community work helps working towards the other strategic goals such as capacity building and training, science of the infrastructure, working with all forms of sensitive data (i.e. not just health data), standards and interop and sharing/co-development of technical solutions?
```

I currently have submitted a title called 'The UK TRE Community - Bringing Together a Fragmented Landscape'

Some questions:
- Is this the right title?
- What do we want to cover?
- Anybody else want to join (it might be too late now but we can ask!)

### Actions

- [x] Prep the content for the lightning talk
- [ ] Review with community feedback
- [ ] Give the talk

**Comment by manics** [comment]
Sounds good to me! I think keep it to one eprson since it's a short/lightning talk. Given that it's a general HDR conference I presume that means the audience may include people with limited knowledge of TREs? So I think keep it general and high level- focussing on building the community, and why it was necessary. But also plug SATRE 😄. E.g. an example of how the UK-TRE community has already supported concrete widely supported outputs that would otherwise only server a limited community, and that this model is driving future WGs. I like the title!

**Comment by harisood** [comment]
Presentation here: https://docs.google.com/presentation/d/1f-iXMm8uyRv4kRtTjxH_qJxh8MISvKa8imSVtmhuCc0/edit?usp=sharing
