### ISSUE TITLE
Create Resources Governance document

### ISSUE THREAD

**Issue by harisood** [uk-tre/community-management#69]
### Detail

We should create a document for how we manage community created resources, meaning those ones that are shared outside any organised community working group

TBH the easiest thing to do may be say 'refer to how we manage working group resources - #19 - and the review process for your resources will be the same (although you aren't an officially a working group).

Link here: https://docs.google.com/document/d/1la5Mwysptkm0AW39uO3DIyR4PEE92AETomjWTJl6g48/edit?usp=sharing

### Actions

- [ ] Create a first draft of this document

**Comment by Davsarper** [comment]
## 27 Feb

- An alternative here is to have a dedicated WG/group who is in charge of managing resources, we might not need another doc in that case
- Or a person, but in general this feels like a responsibility or task rather than a process to set up
- Focus on other docs, if we still see the need for this later go back to this

@harisood as the proponent please continue the discussion and furhter explain why we need this (not closing ideas without a discussion first)

**Comment by harisood** [comment]
J thinking if someone comes not from a WG and says 'my team has created this awesome thing', how we choose to vet it. I think tbh the same process as Working Group outputs works

**Comment by Davsarper** [comment]
@harisood during the last meetings we got to this issue again, I think I recall you had basically done it by reproducing the WG output process but could not find the document. Is this issue done?

**Comment by Davsarper** [comment]
Done https://uk-tre.github.io/hugo-website/about/governance/resources/
