### ISSUE TITLE
Purchase some UK TRE Community merch

### ISSUE THREAD

**Issue by harisood** [uk-tre/community-management#75]
### Detail

We currently have an underspend of approx £1k from the community grant. It's been floated we could get some UK TRE Community merch which is a cool idea!

We work with a design company at Turing called Scriberia. We're going to see if they can create a design for us with which we can make some roll-up banners. If not/time frame doesn't work etc., we'l;l look to buy some merch to distribute in September

Update: we did contract Scriberia who is producing an illustration, this should be usable in banners, stickers and website.

**Key dates:**
- 25 March: last day for Turing to request its Finance department to create the invoice for the grant (i.e. all and exact expenditure known)
- 21 March: make payment for or accrue it (know exactly how much)
- 19 March: target date for illustrations and community review
- 15 March: produce Purchase Order for illustrations
- 14 March: brief for illustrations ready and Scriberia contacted

Note that once exact quantities are known invoices can be produced but payment can have *some* wiggle room

### Actions

- [x] Create brief for Scriberia
- [x] Share brief with Scriberia and see if it's possible
- [x] Determine total cost
- [ ] IF POSSIBLE
  - [ ] Review illustration with CMWG
  - [ ] Design banners with illustration
  - [ ] Review banner design with CMWG
  - [ ] Order banners
- [ ] IF NOT POSSIBLE (or if cost above allows for extra merch)
  - [ ] Decide community merch to purchase
  - [ ] Design merch
  - [ ] Review design with CMWG
  - [ ] Purchase merch

**Comment by manics** [comment]
If the merch is a non-trivial cost could we subsidise it instead? People are likely to appreciate things more when they've had to contribute even if it's a token amount.

Otherwise probably buy a stash of merch to hand out at in-person conferences/events over the next year or two?

**Comment by Davsarper** [comment]
- [ ] @Davsarper to look into logistics and possibility of subsidizing, it would have to be via expenses most likely and happen beofre end of March
- [ ] Open suggestions for other merch

**Comment by Davsarper** [comment]
This is what RSE use https://socrse.myspreadshop.co.uk/

**Comment by Davsarper** [comment]
I have asked spreadshop about how they work and if it would support our usecase. Also asked at Turing if anyone had experience but none so far

**Comment by manics** [comment]
One more idea, buy something like banners, tablecloths, or [flags](https://www.creative-solutions-direct.co.uk/shop/category/flags) to use at events... though it requires someone to store them.

**Comment by Davsarper** [comment]
I do like this idea!

**Comment by Davsarper** [comment]
Anyone up for doing a design? I could also try and quickly contract an illustrator

**Comment by harisood** [comment]
> One more idea, buy something like banners, tablecloths, or [flags](https://www.creative-solutions-direct.co.uk/shop/category/flags) to use at events... though it requires someone to store them.

This could be a good idea! @Davsarper would this need to be done before the end of March?

**Comment by Davsarper** [comment]
CMWG seems to agree with this idea, but it will be important to get a proper design that we do like rather than just doing something because there are funds

**Comment by Davsarper** [comment]
Fall back option will be merch to hand out at the September event

**Comment by Davsarper** [comment]
# Progress update and conversation record

We contracted Scriberia after positive community feedback on slack and the mailing list and had a briefing call with them, we used this document as brief for them https://hackmd.io/QxesdBiwSKSa4WON6-mi3w?view . 
We made an emphasis on collaboration, openness and reproducibility and on building a conveying space together in which we can all share and create resources.
We also clarified that we did not want to be seen building just one specific thing.

Scriberia then produced a first draft which is available in the mailing list and community slack (as a working doc I prefer not to publicily share here, but ask for it).

Feedback from the community agrees that the first draft while it shows people together it lacks specificity about TREs/research with sensitive data, which they did not see represented. Some values like openness are dificult to perceive due to the feeling of closed walls. A few members also clearly saw a space station, in a 2021 fashion, which was not intended and it is not representative.

During the feedback call with Scriberia to address this @Davsarper shared this feedback asking for a more clear inclussion of representative elements/visual cues. Scriberia also shared their vision for the illustration (which if you get if you have been in a call but it is not immediately obvious otherwise): the central part is a library (metaphor suggested by @harisood and @Davsarper ) to which everyone inside is contributing, the little hexagons are different kind of resources that each member is taking back and using to build different solutions which are represented in the outer elements, one represents safety and another openness.

It was agreed the next iteration will include clearer visual cues, make the library/shared space more evident and less spacey, and double down on sharing and connectedness. Some of these elements are:
-	Safety and trust 
-	Security
-	Privacy
-	Governance and standards: maybe those instructions you mentioned, or checklists/recipes
-	Operational capacity: the tools to do research (usable and productive), which may boil down to the infrastructure/computers/cloud environments to work in

**Comment by Davsarper** [comment]
Reach out to public members who we are already in contact with for feedback. Prepare a simple form for people to give feedback

**Comment by Davsarper** [comment]
After feedback from the community I sent Scriberia this feedback:

Feedback:
•	Some members have found the new draft a bit crowded and difficult to interpret. I think there is a difficult balance here, the image does convey the elements we asked for previously and shows the complexity of the TRE space and community. I wonder if there is a way of alleviating the “busyness” feeling some have expressed. I will let you as experts consider this, and what can work best for the intended use (banners, webpage along supporting text).
•	Keep characters to their sections: I really like how characters reaching into the centre and across areas convey collaboration and connectedness, as well as “taking what they need” from the central space that is the community. But due to the sensitive nature of data in the TRE space someone has pointed out it can be read as data/records being taken out of where they should be. Despite personal preference I think they are right, and we have to ensure others (especially the public) does not read that into the image.
o	Can the same characters that are reaching into the centres be moved wholly into their sections?
o	Can you rotate vertically the person with the laptop so they face the hexagon?
o	This also may simplify the central hexagon for use on its own.
•	To counter the above suggestion downplaying collaboration, and the impression silos. Would it work to remove the solid lines between areas or making them dotted? Unsure of how that then works in practice for using the image.
o	Someone has also suggested bringing back speech bubbles or a symbol for ideas, to keep the main message of knowledge sharing. Do you think it would work? To me the central figures are clearly speaking already, but if there is an effective way of reinforcing this please do.
•	Change the construction worker character: this was totally our idea originally, but with the current design it is difficult to interpret why a construction worker is seating at the table in the centre. Can you use another character?
•	Central font: I never got back with the font that we use in the current logo sorry, but it would be good to better align with it I think? I attach the logo.
•	Is there too much black in the centre? This has been pointed out and I agree. Unsure if there should be no black at all or just change the letters.
•	Gear in operational capacity and label: I used this term in my email below but looking at it I wonder if using the ‘ceros and ones’ or a line graph along the label ‘research capacity’ (or simply research) may help focus the image better and convey ‘safe environments for sensitive data’ as a whole.
o	I have also a nagging feeling that placing the figure resembling a Hindu/Sikh person along the most IT looking area is too close of a stereotype.
•	Text labels: I understand we will have a version with no text, and also the working file right? In that case we can play with exact text.
•	Order of sections: it may be read better and also has thematic sense to order sections as (start at right, then clockwise)
o	Security
o	Safety and trust
o	Privacy
o	Research (capacity) [op capacity]
o	Governance & standards
o	Reproducibility
•	Small details: there are lines going into text and that sort of little details, but I guess that is what you meant with polishing so will not go there now.

And then talked to them on Friday, in summary 

We discussed the proposed changes and what was possible, a full reordering of sections was not possible with the time left due to how the illustration was built (hand drawn with sections linked to each other) but we agreed to put safety and trust as the “first” (top left) section and change the operational capacity one into ‘research’.

The rest of the feedback they were going to apply, taking into account that simplicity and less connections between sections downplay connectivity and openness so there is a necessary balance. To simplify some lines will be taken out and characters kept to their sections.

We decided not to add any more speech bubbles as they complicated the image and again we would have things going across sections, to still reinforce the idea of talking the central characters will be more obviously talking (opening their mouths).

**Comment by Davsarper** [comment]
I received the Illustration from Scriberia yesterday, including editable file for modifications (I think I (Turing) will have to gatekeep that probably). It applies the feedback as much as possible (it is not in anyway a redo) and I do like the results.
Yet I have asked Scriberia for one last important change, despite there not being feedback rounds left they have agreed to apply it. We noticed that despite diverse characters present in the illustration only the most normative/white looking ones where seated at the central table, so they will work on changing the "guy" in the centre again to give a clearer message of inclusion. This will take a few days for them to do properly and because they had no time planned for it, I will share the final version as we get it.

**Comment by harisood** [comment]
You're a hero @Davsarper !!

**Comment by manics** [comment]
Illustration finalised, then can buy banners.

**Comment by Davsarper** [comment]
Banner in progress here https://www.canva.com/design/DAGIGWNzzn4/tPCm88u8vwNigVspxITogA/edit?utm_content=DAGIGWNzzn4&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton

**Comment by Davsarper** [comment]
What do we think of current pages 1 and 2 on that link? @manics @balintstewart77 @hardakerm

**Comment by manics** [comment]
They both look good, I prefer page 2 though.
The Youtube logo looks a bit too small and unaligned, and I think it'd be worth making the web address more prominent, e.g. make it bold?

**Comment by Davsarper** [comment]
Ah, I was getting consensus on 2 (no dark blue) elsewhere. I will try to get a vote, but if we like the overall design we can move forward.

And yes, youtube logo is small and there are other mislignments. Now we have a draft I will do it properly

**Comment by hardakerm** [comment]
Do we capitalise "Community"? I'd probably say yes, but I don't have strong feelings. I think I prefer the white background, but again no strong feelings.

**Comment by manics** [comment]
For September meeting: also get more hexagon stickers

**Comment by Davsarper** [comment]
got the illustration, produced stickers and 2 awesome banners
